import * as Automerge from "@automerge/automerge";
import type { DocumentId } from "@automerge/automerge-repo";
import type { FastifyInstance } from "fastify";
import { hasScope, requireAuth } from "../auth/middleware.ts";
import {
  checkBlobQuota,
  checkDocumentCreationQuota,
  checkDocumentSizeQuota,
  checkTotalStorageQuota,
} from "../lib/quotas.ts";
import { parseDocumentId } from "../lib/types.ts";
import {
  createDocument,
  createDocumentBlobClaim,
  deleteDocument,
  deleteDocumentBlobClaim,
  getAccessibleDocuments,
  getAppDocument,
  getBlob,
  getDocument,
  getDocumentACL,
  getDocumentBlobClaim,
  getDocumentBlobClaims,
  getDocumentByAutomergeId,
  getDocumentsByOwner,
  getUser,
  getUserBlobStorageUsed,
  getUserDocumentCount,
  getUserTotalStorage,
  setAppDocument,
  setDocumentACL,
  updateDocumentExpiration,
  updateDocumentSize,
  updateDocumentType,
} from "../storage/database.ts";
import { getRepo, getStorageAdapter } from "../sync/repo.ts";
import {
  createDocumentSchema,
  updateDocumentAclSchema,
  updateDocumentExpirationSchema,
  updateDocumentTypeSchema,
} from "./schemas.ts";

export async function documentRoutes(fastify: FastifyInstance): Promise<void> {
  // Get/Create App Document
  fastify.get(
    "/app/:appId",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { appId } = request.params as { appId: string };
      const userId = request.auth!.userId;

      if (!/^[a-zA-Z0-9._-]+$/.test(appId)) {
        return reply.code(400).send({
          error: "invalid_request",
          message: "Invalid App ID",
        });
      }

      let docId = getAppDocument(userId, appId);
      let needsCreation = !docId;

      // If document ID exists, verify it actually exists in storage (chunks)
      // This handles the case where metadata exists but content was lost/not saved
      if (docId) {
        const existingDoc = getDocument(docId);
        if (!existingDoc) {
          needsCreation = true;
        } else {
          const storage = getStorageAdapter();
          const syncDocumentId = getSyncDocumentId(existingDoc);
          const snapshot = await storage.load([syncDocumentId]);
          const chunks = await storage.loadRange([syncDocumentId]);

          if (!snapshot && chunks.length === 0) {
            request.log.warn(
              `App document ${docId} missing from storage, recreating...`,
            );
            needsCreation = true;
          }
        }
      }

      if (needsCreation) {
        const repo = getRepo();
        // Initialize with basic metadata to ensure it's persisted
        const handle = repo.create({ createdAt: new Date().toISOString() });
        const newDocId = handle.url.replace("automerge:", "");

        // Create document record first (or update if we are recovering)
        // If we are recovering, we might want to delete the old one or just update
        if (docId) {
          // Delete old metadata to be clean
          deleteDocument(docId);
        }

        createDocument({
          id: newDocId,
          ownerId: userId,
          type: `app:${appId}`,
          automergeId: newDocId,
        });

        // Link in app_documents
        setAppDocument(userId, appId, newDocId);
        docId = newDocId;
      }

      return { documentId: docId };
    },
  );

  // Create document
  fastify.post("/", { preHandler: requireAuth }, async (request, reply) => {
    if (!hasScope(request.auth!, "documents:write")) {
      return reply.code(403).send({
        error: "insufficient_scope",
        message: 'This action requires the "documents:write" scope',
      });
    }

    const result = createDocumentSchema.safeParse(request.body);
    if (!result.success) {
      reply.code(400).send({
        error: "invalid_request",
        message: result.error.message,
      });
      return;
    }

    let { id, automergeId, type, acl, expiresAt } = result.data;
    const userId = request.auth!.userId;

    let idGenerated = false;
    // Generate ID if not provided
    if (!id) {
      const repo = getRepo();
      const handle = repo.create();
      id = handle.url.replace("automerge:", "");
      idGenerated = true;
    }

    const { prefix } = parseDocumentId(id);

    if (prefix === "app" || type?.startsWith("app:")) {
      reply.code(400).send({
        error: "invalid_request",
        message: "App documents are managed by GET /documents/app/:appId",
      });
      return;
    }

    if (prefix === "eph") {
      reply.code(400).send({
        error: "invalid_request",
        message: "Ephemeral documents cannot be created through the REST API",
      });
      return;
    }

    // If automergeId not provided:
    // 1. If ID was generated by us, use it (it's a valid Automerge ID)
    // 2. If ID was provided by user, it might be a slug/label (like 'doc:my-doc').
    //    In this case, generate a real Automerge ID.
    if (!automergeId) {
      if (idGenerated) {
        automergeId = id;
      } else {
        const repo = getRepo();
        const handle = repo.create();
        automergeId = handle.url.replace("automerge:", "");
      }
    }

    // Check if document already exists
    const existing = getDocument(id);
    if (existing) {
      reply.code(409).send({
        error: "conflict",
        message: "Document already exists",
      });
      return;
    }

    const existingByAutomergeId = getDocumentByAutomergeId(automergeId);
    if (existingByAutomergeId) {
      reply.code(409).send({
        error: "conflict",
        message: "Automerge document ID is already registered",
      });
      return;
    }

    // Check quota
    const user = getUser(userId);
    if (!user) {
      reply.code(500).send({
        error: "internal_error",
        message: "User not found",
      });
      return;
    }

    const quotaCheck = await checkDocumentCreationQuota(
      {
        getUserDocumentCount: async (uid) => getUserDocumentCount(uid),
        getUserTotalStorage: async (uid) => getUserTotalStorage(uid),
      },
      user,
    );

    if (!quotaCheck.allowed) {
      reply.code(403).send({
        error: "quota_exceeded",
        quota: quotaCheck.quota,
        current: quotaCheck.current,
        limit: quotaCheck.limit,
      });
      return;
    }

    // Create document
    const doc = createDocument({
      id,
      ownerId: userId,
      ...(type ? { type } : {}),
      automergeId,
    });

    // Set ACL if provided
    if (acl && acl.length > 0) {
      setDocumentACL(id, acl);
    }

    // Set expiration if provided
    if (expiresAt) {
      updateDocumentExpiration(id, new Date(expiresAt));
    }

    return {
      id: doc.id,
      owner: doc.ownerId,
      type: doc.type,
      acl: acl ?? [],
      createdAt: doc.createdAt.toISOString(),
      expiresAt: expiresAt ?? null,
    };
  });

  // List documents
  fastify.get("/", { preHandler: requireAuth }, async (request, reply) => {
    if (!hasScope(request.auth!, "documents:read")) {
      return reply.code(403).send({
        error: "insufficient_scope",
        message: 'This action requires the "documents:read" scope',
      });
    }

    const userId = request.auth!.userId;

    const owned = getDocumentsByOwner(userId);
    const accessible = getAccessibleDocuments(userId).filter(
      (d) => d.ownerId !== userId && !isAppDocument(d),
    );

    return {
      owned: owned.map(docToResponse),
      accessible: accessible.map(docToResponse),
    };
  });

  // Get document metadata
  fastify.get("/:id", { preHandler: requireAuth }, async (request, reply) => {
    if (!hasScope(request.auth!, "documents:read")) {
      return reply.code(403).send({
        error: "insufficient_scope",
        message: 'This action requires the "documents:read" scope',
      });
    }

    const { id } = request.params as { id: string };
    const userId = request.auth!.userId;

    const doc = getDocument(id);
    if (!doc) {
      reply.code(404).send({
        error: "not_found",
        message: "Document not found",
      });
      return;
    }

    if (!canReadDocument(doc, userId)) {
      reply.code(403).send({
        error: "forbidden",
        message: "Access denied",
      });
      return;
    }

    return {
      ...docToResponse(doc),
      ...(doc.ownerId === userId ? { acl: getDocumentACL(id) } : {}),
    };
  });

  // Export document content
  fastify.get(
    "/:id/export",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id } = request.params as { id: string };
      const { format } = request.query as { format?: string };
      const userId = request.auth!.userId;

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (!canReadDocument(doc, userId)) {
        reply.code(403).send({
          error: "forbidden",
          message: "Access denied",
        });
        return;
      }

      const data = await exportDocumentBinary(doc);
      if (!data) {
        // Empty document or file missing
        if (format === "json") {
          return {};
        }
        return reply
          .header("Content-Type", "application/octet-stream")
          .send(new Uint8Array(0));
      }

      if (format === "json") {
        try {
          const automergeDoc = Automerge.load(data);
          return Automerge.view(automergeDoc, Automerge.getHeads(automergeDoc));
        } catch (err) {
          reply.code(500).send({
            error: "internal_error",
            message: `Failed to parse document: ${(err as Error).message}`,
          });
          return;
        }
      } else {
        // Binary
        reply
          .header("Content-Type", "application/octet-stream")
          .header("Content-Disposition", `attachment; filename="${id}.amrg"`);
        return reply.send(data);
      }
    },
  );

  // Update document content (from JSON)
  fastify.put(
    "/:id/content",
    { preHandler: requireAuth },
    async (request, reply) => {
      if (!hasScope(request.auth!, "documents:write")) {
        return reply.code(403).send({
          error: "insufficient_scope",
          message: 'This action requires the "documents:write" scope',
        });
      }

      const { id } = request.params as { id: string };
      const userId = request.auth!.userId;
      const newContent = request.body as Record<string, unknown>;

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (!canWriteDocument(doc, userId)) {
        reply.code(403).send({
          error: "forbidden",
          message: "Access denied",
        });
        return;
      }

      // Load existing or create new
      const syncDocumentId = getSyncDocumentId(doc);
      const data = await getRepo().export(syncDocumentId);
      let automergeDoc: Automerge.Doc<unknown>;

      try {
        if (data && data.length > 0) {
          automergeDoc = Automerge.load(data);
        } else {
          automergeDoc = Automerge.init();
        }

        // Apply changes
        // biome-ignore lint/suspicious/noExplicitAny: Automerge document root is dynamic
        automergeDoc = Automerge.change(automergeDoc, (d: any) => {
          // Clear existing keys
          for (const key of Object.keys(d)) {
            delete d[key];
          }
          // Set new keys
          Object.assign(d, newContent);
        });

        const newData = Automerge.save(automergeDoc);

        const owner = getUser(doc.ownerId);
        if (!owner) {
          reply.code(500).send({
            error: "internal_error",
            message: "Document owner not found",
          });
          return;
        }

        const sizeCheck = checkDocumentSizeQuota(owner, newData.length);
        if (!sizeCheck.allowed) {
          reply.code(403).send({
            error: "quota_exceeded",
            quota: sizeCheck.quota,
            current: sizeCheck.current,
            limit: sizeCheck.limit,
          });
          return;
        }

        const additionalSize = Math.max(0, newData.length - doc.size);
        if (additionalSize > 0) {
          const totalStorageCheck = await checkTotalStorageQuota(
            {
              getUserDocumentCount: async () => 0,
              getUserTotalStorage: async (uid) => getUserTotalStorage(uid),
            },
            owner,
            additionalSize,
          );

          if (!totalStorageCheck.allowed) {
            reply.code(403).send({
              error: "quota_exceeded",
              quota: totalStorageCheck.quota,
              current: totalStorageCheck.current,
              limit: totalStorageCheck.limit,
            });
            return;
          }
        }

        getRepo().import(newData, { docId: syncDocumentId as DocumentId });
        updateDocumentSize(id, newData.length);

        return { success: true, size: newData.length };
      } catch (err) {
        reply.code(500).send({
          error: "internal_error",
          message: `Failed to update document: ${(err as Error).message}`,
        });
        return;
      }
    },
  );

  // Delete document
  fastify.delete(
    "/:id",
    { preHandler: requireAuth },
    async (request, reply) => {
      if (!hasScope(request.auth!, "documents:write")) {
        return reply.code(403).send({
          error: "insufficient_scope",
          message: 'This action requires the "documents:write" scope',
        });
      }

      const { id } = request.params as { id: string };
      const userId = request.auth!.userId;

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (doc.ownerId !== userId) {
        reply.code(403).send({
          error: "forbidden",
          message: "Only the owner can delete a document",
        });
        return;
      }

      await getStorageAdapter().removeRange([getSyncDocumentId(doc)]);
      deleteDocument(id);

      reply.code(204).send();
    },
  );

  // Update ACL
  fastify.put(
    "/:id/acl",
    { preHandler: requireAuth },
    async (request, reply) => {
      if (!hasScope(request.auth!, "documents:write")) {
        return reply.code(403).send({
          error: "insufficient_scope",
          message: 'This action requires the "documents:write" scope',
        });
      }

      const { id } = request.params as { id: string };
      const userId = request.auth!.userId;

      const result = updateDocumentAclSchema.safeParse(request.body);
      if (!result.success) {
        reply.code(400).send({
          error: "invalid_request",
          message: result.error.message,
        });
        return;
      }

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (doc.ownerId !== userId) {
        reply.code(403).send({
          error: "forbidden",
          message: "Only the owner can modify ACL",
        });
        return;
      }

      if (isAppDocument(doc)) {
        reply.code(400).send({
          error: "invalid_request",
          message: "App documents cannot have ACL entries",
        });
        return;
      }

      setDocumentACL(id, result.data.acl);

      return { acl: result.data.acl };
    },
  );

  // Get ACL
  fastify.get(
    "/:id/acl",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id } = request.params as { id: string };
      const userId = request.auth!.userId;

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      // Only owner can view ACL
      if (doc.ownerId !== userId) {
        reply.code(403).send({
          error: "forbidden",
          message: "Only the owner can view ACL",
        });
        return;
      }

      return { acl: getDocumentACL(id) };
    },
  );

  // Update type
  fastify.put(
    "/:id/type",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id } = request.params as { id: string };
      const userId = request.auth!.userId;

      const result = updateDocumentTypeSchema.safeParse(request.body);
      if (!result.success) {
        reply.code(400).send({
          error: "invalid_request",
          message: result.error.message,
        });
        return;
      }

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (doc.ownerId !== userId) {
        reply.code(403).send({
          error: "forbidden",
          message: "Only the owner can change document type",
        });
        return;
      }

      updateDocumentType(id, result.data.type);

      return { type: result.data.type };
    },
  );

  // Update expiration
  fastify.put(
    "/:id/expiration",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id } = request.params as { id: string };
      const userId = request.auth!.userId;

      const result = updateDocumentExpirationSchema.safeParse(request.body);
      if (!result.success) {
        reply.code(400).send({
          error: "invalid_request",
          message: result.error.message,
        });
        return;
      }

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (doc.ownerId !== userId) {
        reply.code(403).send({
          error: "forbidden",
          message: "Only the owner can set expiration",
        });
        return;
      }

      const expiresAt = result.data.expiresAt
        ? new Date(result.data.expiresAt)
        : null;
      updateDocumentExpiration(id, expiresAt);

      return { expiresAt: expiresAt?.toISOString() ?? null };
    },
  );

  // Get document history
  fastify.get(
    "/:id/history",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id } = request.params as { id: string };
      const { limit = "50", offset = "0" } = request.query as {
        limit?: string;
        offset?: string;
      };
      const userId = request.auth!.userId;

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (!canReadDocument(doc, userId)) {
        reply.code(403).send({
          error: "forbidden",
          message: "Access denied",
        });
        return;
      }

      const data = await exportDocumentBinary(doc);
      if (!data || data.length === 0) {
        return {
          changes: [],
          totalChanges: 0,
          currentHeads: [],
        };
      }

      try {
        const automergeDoc = Automerge.load(data);
        const history = Automerge.getHistory(automergeDoc);
        const currentHeads = Automerge.getHeads(automergeDoc);

        const limitNum = Math.min(Math.max(1, parseInt(limit, 10) || 50), 100);
        const offsetNum = Math.max(0, parseInt(offset, 10) || 0);

        // Map history to change entries (most recent first)
        const allChanges = history
          .map((state, index) => {
            const change = state.change;
            return {
              hash: change.hash,
              actor: change.actor,
              seq: change.seq,
              timestamp: change.time
                ? new Date(change.time * 1000).toISOString()
                : null,
              message: change.message || null,
              opsCount: change.ops?.length ?? 0,
              index,
            };
          })
          .reverse();

        const paginatedChanges = allChanges.slice(
          offsetNum,
          offsetNum + limitNum,
        );

        return {
          changes: paginatedChanges,
          totalChanges: allChanges.length,
          currentHeads: currentHeads.map((h) => h),
        };
      } catch (err) {
        reply.code(500).send({
          error: "internal_error",
          message: `Failed to load history: ${(err as Error).message}`,
        });
        return;
      }
    },
  );

  // Get document snapshot at specific heads
  fastify.get(
    "/:id/snapshot",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id } = request.params as { id: string };
      const { heads } = request.query as { heads?: string };
      const userId = request.auth!.userId;

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (!canReadDocument(doc, userId)) {
        reply.code(403).send({
          error: "forbidden",
          message: "Access denied",
        });
        return;
      }

      if (!heads) {
        reply.code(400).send({
          error: "invalid_request",
          message: "Missing heads parameter",
        });
        return;
      }

      const data = await exportDocumentBinary(doc);
      if (!data || data.length === 0) {
        reply.code(404).send({
          error: "not_found",
          message: "Document has no content",
        });
        return;
      }

      try {
        const automergeDoc = Automerge.load(data);
        const headsList = heads.split(",").filter((h) => h.trim());

        const snapshot = Automerge.view(automergeDoc, headsList);

        return {
          heads: headsList,
          snapshot,
        };
      } catch (err) {
        reply.code(500).send({
          error: "internal_error",
          message: `Failed to load snapshot: ${(err as Error).message}`,
        });
        return;
      }
    },
  );

  // Get diff between two versions
  fastify.get(
    "/:id/diff",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id } = request.params as { id: string };
      const { from, to } = request.query as { from?: string; to?: string };
      const userId = request.auth!.userId;

      const doc = getDocument(id);
      if (!doc) {
        reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
        return;
      }

      if (!canReadDocument(doc, userId)) {
        reply.code(403).send({
          error: "forbidden",
          message: "Access denied",
        });
        return;
      }

      if (!from) {
        reply.code(400).send({
          error: "invalid_request",
          message: "Missing from parameter",
        });
        return;
      }

      const data = await exportDocumentBinary(doc);
      if (!data || data.length === 0) {
        reply.code(404).send({
          error: "not_found",
          message: "Document has no content",
        });
        return;
      }

      try {
        const automergeDoc = Automerge.load(data);
        const currentHeads = Automerge.getHeads(automergeDoc);

        // Handle "initial" as empty heads (document start)
        const fromHeads =
          from === "initial" ? [] : from.split(",").filter((h) => h.trim());
        const toHeads = to
          ? to.split(",").filter((h) => h.trim())
          : currentHeads;

        const patches = Automerge.diff(automergeDoc, fromHeads, toHeads);

        return {
          from: fromHeads,
          to: toHeads,
          patches,
        };
      } catch (err) {
        reply.code(500).send({
          error: "internal_error",
          message: `Failed to compute diff: ${(err as Error).message}`,
        });
        return;
      }
    },
  );

  // Document blob claims

  // Add document claim on blob
  fastify.post(
    "/:id/blobs/:hash",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id, hash } = request.params as { id: string; hash: string };
      const userId = request.auth!.userId;

      // Validate hash format
      if (!/^[a-f0-9]{64}$/.test(hash)) {
        return reply.code(400).send({
          error: "invalid_request",
          message: "Invalid blob hash format",
        });
      }

      // Get document
      const doc = getDocument(id);
      if (!doc) {
        return reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
      }

      if (!canWriteDocument(doc, userId)) {
        return reply.code(403).send({
          error: "forbidden",
          message: "Write access required to add blob claims",
        });
      }

      // Get blob
      const blob = getBlob(hash);
      if (!blob) {
        return reply.code(404).send({
          error: "not_found",
          message: "Blob not found",
        });
      }

      // Check if already claimed by this document
      const existingClaim = getDocumentBlobClaim(hash, id);
      if (existingClaim) {
        return reply.code(409).send({
          error: "already_claimed",
          message: "Document has already claimed this blob",
        });
      }

      // Check quota for document owner
      const owner = getUser(doc.ownerId);
      if (!owner) {
        return reply.code(500).send({
          error: "internal_error",
          message: "Document owner not found",
        });
      }

      const quotaCheck = await checkBlobQuota(
        { getUserBlobStorageUsed: async (uid) => getUserBlobStorageUsed(uid) },
        owner,
        blob.size,
      );

      if (!quotaCheck.allowed) {
        return reply.code(402).send({
          error: "quota_exceeded",
          message: "Document owner's blob quota exceeded",
          quota: quotaCheck.quota,
          current: quotaCheck.current,
          limit: quotaCheck.limit,
          required: blob.size,
        });
      }

      // Create document claim
      const claim = createDocumentBlobClaim(hash, id, doc.ownerId);

      return reply.code(200).send({
        hash: blob.hash,
        size: blob.size,
        mimeType: blob.mimeType,
        documentId: claim.documentId,
        claimedAt: claim.claimedAt.toISOString(),
      });
    },
  );

  // Remove document claim on blob
  fastify.delete(
    "/:id/blobs/:hash",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id, hash } = request.params as { id: string; hash: string };
      const userId = request.auth!.userId;

      // Validate hash format
      if (!/^[a-f0-9]{64}$/.test(hash)) {
        return reply.code(400).send({
          error: "invalid_request",
          message: "Invalid blob hash format",
        });
      }

      // Get document
      const doc = getDocument(id);
      if (!doc) {
        return reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
      }

      if (!canWriteDocument(doc, userId)) {
        return reply.code(403).send({
          error: "forbidden",
          message: "Write access required to remove blob claims",
        });
      }

      // Check if claimed
      const existingClaim = getDocumentBlobClaim(hash, id);
      if (!existingClaim) {
        return reply.code(404).send({
          error: "not_found",
          message: "Document has not claimed this blob",
        });
      }

      // Delete claim
      deleteDocumentBlobClaim(hash, id);

      return reply.code(204).send();
    },
  );

  // List blobs claimed by document
  fastify.get(
    "/:id/blobs",
    { preHandler: requireAuth },
    async (request, reply) => {
      const { id } = request.params as { id: string };
      const userId = request.auth!.userId;

      // Get document
      const doc = getDocument(id);
      if (!doc) {
        return reply.code(404).send({
          error: "not_found",
          message: "Document not found",
        });
      }

      if (!canReadDocument(doc, userId)) {
        return reply.code(403).send({
          error: "forbidden",
          message: "Access denied",
        });
      }

      // Get document blob claims
      const claims = getDocumentBlobClaims(id);
      let totalSize = 0;

      const blobs = claims
        .map((claim) => {
          const blob = getBlob(claim.blobHash);
          if (!blob) return null;
          totalSize += blob.size;
          return {
            hash: blob.hash,
            size: blob.size,
            mimeType: blob.mimeType,
            claimedAt: claim.claimedAt.toISOString(),
          };
        })
        .filter(Boolean);

      return reply.code(200).send({
        blobs,
        totalSize,
      });
    },
  );
}

type StoredDocument = {
  id: string;
  ownerId: string;
  automergeId: string | null;
  type: string;
};

function isAppDocument(doc: { type: string | null }): boolean {
  return typeof doc.type === "string" && doc.type.startsWith("app:");
}

function canReadDocument(doc: StoredDocument, userId: string): boolean {
  if (doc.ownerId === userId) {
    return true;
  }

  if (isAppDocument(doc)) {
    return false;
  }

  const acl = getDocumentACL(doc.id);
  return acl.some(
    (entry) =>
      (entry.principal === userId || entry.principal === "public") &&
      (entry.permission === "read" || entry.permission === "write"),
  );
}

function canWriteDocument(doc: StoredDocument, userId: string): boolean {
  if (doc.ownerId === userId) {
    return true;
  }

  if (isAppDocument(doc)) {
    return false;
  }

  const acl = getDocumentACL(doc.id);
  return acl.some(
    (entry) =>
      (entry.principal === userId || entry.principal === "public") &&
      entry.permission === "write",
  );
}

function getSyncDocumentId(doc: StoredDocument): DocumentId {
  return (doc.automergeId ?? doc.id) as DocumentId;
}

async function exportDocumentBinary(
  doc: StoredDocument,
): Promise<Uint8Array | null> {
  const data = await getRepo().export(getSyncDocumentId(doc));
  return data ?? null;
}

function docToResponse(doc: {
  id: string;
  ownerId: string;
  type: string;
  size: number;
  expiresAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}) {
  return {
    id: doc.id,
    owner: doc.ownerId,
    type: doc.type,
    size: doc.size,
    expiresAt: doc.expiresAt?.toISOString() ?? null,
    createdAt: doc.createdAt.toISOString(),
    updatedAt: doc.updatedAt.toISOString(),
  };
}
