#!/usr/bin/env bun
/**
 * Build script for creating a standalone binary executable.
 *
 * This script:
 * 1. Builds the browser client bundle
 * 2. Generates an entry point that embeds all UI files
 * 3. Compiles everything into a standalone binary
 */

import { execSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";

const ROOT_DIR = join(import.meta.dir, "..");
const SRC_DIR = join(ROOT_DIR, "src");
const UI_DIR = join(SRC_DIR, "ui");
const DIST_DIR = join(ROOT_DIR, "dist");
const CLIENT_DIR = join(ROOT_DIR, "client");

// Ensure dist directory exists
if (!existsSync(DIST_DIR)) {
  mkdirSync(DIST_DIR, { recursive: true });
}

console.log("=== Building Ratatoskr Binary ===\n");

// Step 1: Build the client bundle
console.log("Step 1: Building client bundle...");
execSync("bun install --frozen-lockfile", {
  cwd: CLIENT_DIR,
  stdio: "inherit",
});
execSync("bun run build:bundle", { cwd: CLIENT_DIR, stdio: "inherit" });
console.log("Client bundle built.\n");

// Step 2: Collect all UI files to embed
console.log("Step 2: Collecting UI files to embed...");

function getAllFiles(dir: string, basePath: string = dir): string[] {
  const files: string[] = [];
  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...getAllFiles(fullPath, basePath));
    } else {
      files.push(relative(basePath, fullPath));
    }
  }

  return files;
}

const uiFiles = getAllFiles(UI_DIR);
console.log(`Found ${uiFiles.length} UI files to embed:`);
for (const file of uiFiles) {
  console.log(`  - ${file}`);
}
console.log();

// Step 3: Generate the binary entry point
console.log("Step 3: Generating binary entry point...");

const imports = uiFiles
  .map(
    (file, i) =>
      `import file${i} from "./src/ui/${file}" with { type: "file" };`,
  )
  .join("\n");

const fileMap = uiFiles
  .map((file, i) => `  "${file.replace(/\\/g, "/")}": file${i},`)
  .join("\n");

const entryPoint = `/**
 * Auto-generated entry point for standalone binary.
 * DO NOT EDIT - This file is generated by scripts/build-binary.ts
 */

// Import all UI files for embedding
${imports}

// Import the embedded files helper to register the files
import { setEmbeddedFiles } from "./src/lib/embedded-files.ts";

// Register embedded files before anything else
const embeddedUIFiles: Record<string, string> = {
${fileMap}
};
setEmbeddedFiles(embeddedUIFiles);

// Now run the main entry point
import "./src/index.ts";
`;

const entryPointPath = join(ROOT_DIR, "binary-entry.ts");
writeFileSync(entryPointPath, entryPoint);
console.log("Generated binary-entry.ts\n");

// Step 4: Compile the binary
console.log("Step 4: Compiling binary...");

const outputName = process.platform === "win32" ? "ratatoskr.exe" : "ratatoskr";
const outputPath = join(DIST_DIR, outputName);

execSync(
  `bun build --compile --minify --sourcemap=none --asset-naming="[name].[ext]" --outfile="${outputPath}" ./binary-entry.ts`,
  { cwd: ROOT_DIR, stdio: "inherit" },
);

console.log(`\nBinary compiled: ${outputPath}`);

// Step 5: Clean up temporary files
console.log("\nStep 5: Cleaning up...");
execSync(`rm -f "${entryPointPath}"`, { cwd: ROOT_DIR });
console.log("Cleaned up temporary files.\n");

// Report binary size
const binarySize = statSync(outputPath).size;
const sizeMB = (binarySize / 1024 / 1024).toFixed(2);
console.log(`=== Build Complete ===`);
console.log(`Binary: ${outputPath}`);
console.log(`Size: ${sizeMB} MB`);
